### ISSUE TITLE
Make Support To 6.0

### ISSUE THREAD

**Issue by pharidali** [ittianyu/MobileGuard#1]
Please make supoort Cache Clean and Message Safe To 6.0

**Comment by ittianyu** [comment]
I have tried before. but I found that only system app can do these operations since 6.0.

**Comment by pharidali** [comment]
Ok. Please add Pattern lock system.

**Comment by pharidali** [comment]
Clean Master run on all the devices. but Your product not run.. 
How It Possible??

**Comment by ittianyu** [comment]
Sorry, I can't do that now.

**Comment by pharidali** [comment]
ok.. Best of luck..
